"use client";

import { icons } from "@sanity/icons";
import {
  Badge,
  Box,
  Card,
  Flex,
  Stack,
  Text,
  TextInput,
} from "@sanity/ui";
import { useMemo, useState } from "react";
import type { Tool } from "sanity";

import index from "@/design/tokens.index.json";

/*
  "Design tokens" — the Studio's read-only view of the design system,
  laid out like Figma's Variables panel: rows of tokens, one column
  per mode, resolved values with swatches.

  Two tabs:
    · Site tokens   — what the code actually consumes (globals.css):
                      semantic colors per section mode, the spacing
                      scale, the fluid type scale, radii, fonts. Each
                      row carries the utility class to build with.
    · Figma library — the raw variable collection exported from the
                      Figma file, every mode, aliases noted.

  The data is generated by `npm run tokens` (scripts/build-token-
  index.mjs) into src/design/tokens.index.json, which also records
  when each source was last re-exported — shown in the header.
*/

type Row = {
  path: string;
  name: string;
  type: string;
  values?: Record<string, string>;
  value?: string;
  aliasOf?: Record<string, string>;
  utility?: string | null;
  detail?: { lineHeight?: string; letterSpacing?: string };
};

const MONO = "ui-monospace, SFMono-Regular, Menlo, monospace";

const isColor = (v?: string) =>
  !!v && /^(#|rgb|hsl|color\()/i.test(v.trim());

function relativeTime(iso?: string | null) {
  if (!iso) return "unknown";
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return "unknown";
  const days = Math.floor((Date.now() - then) / 86_400_000);
  const date = new Date(iso).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  if (days <= 0) return `${date} (today)`;
  if (days === 1) return `${date} (yesterday)`;
  return `${date} (${days} days ago)`;
}

function Swatch({ value }: { value: string }) {
  return (
    <span
      aria-hidden
      style={{
        display: "inline-block",
        width: 14,
        height: 14,
        flex: "none",
        borderRadius: 2,
        background: value,
        boxShadow: "inset 0 0 0 1px rgba(128,128,128,0.35)",
        /* alpha tokens read correctly over a checker */
        backgroundImage: `linear-gradient(${value}, ${value}), repeating-conic-gradient(#bbb 0% 25%, #fff 0% 50%)`,
        backgroundSize: "auto, 8px 8px",
      }}
    />
  );
}

/* one token = one row; a cell per mode */
function TokenRow({ row, modes }: { row: Row; modes: string[] }) {
  const single = row.value !== undefined;
  return (
    <Flex
      align="flex-start"
      gap={3}
      paddingY={2}
      paddingX={3}
      style={{ borderBottom: "1px solid var(--card-border-color)" }}
    >
      <Box style={{ width: 230, flex: "none" }}>
        <Stack space={2}>
          <Text size={1} weight="medium" style={{ fontFamily: MONO }}>
            {row.name}
          </Text>
          {row.utility && (
            <Text size={0} muted style={{ fontFamily: MONO }}>
              {row.utility}
            </Text>
          )}
        </Stack>
      </Box>

      {single ? (
        <Box flex={1}>
          <Stack space={2}>
            <Text size={1} style={{ fontFamily: MONO }}>
              {row.value}
            </Text>
            {(row.detail?.lineHeight || row.detail?.letterSpacing) && (
              <Text size={0} muted style={{ fontFamily: MONO }}>
                {row.detail?.lineHeight && `line-height ${row.detail.lineHeight}`}
                {row.detail?.lineHeight && row.detail?.letterSpacing && "  ·  "}
                {row.detail?.letterSpacing && `tracking ${row.detail.letterSpacing}`}
              </Text>
            )}
          </Stack>
        </Box>
      ) : (
        modes.map((mode) => {
          const v = row.values?.[mode];
          const alias = row.aliasOf?.[mode];
          return (
            <Box key={mode} flex={1} style={{ minWidth: 0 }}>
              {v ? (
                <Stack space={2}>
                  <Flex align="center" gap={2}>
                    {isColor(v) && <Swatch value={v} />}
                    <Text
                      size={1}
                      textOverflow="ellipsis"
                      style={{ fontFamily: MONO }}
                    >
                      {v}
                    </Text>
                  </Flex>
                  {alias && (
                    <Text size={0} muted textOverflow="ellipsis" title={alias}>
                      → {alias.split("/").pop()}
                    </Text>
                  )}
                </Stack>
              ) : (
                <Text size={1} muted>
                  —
                </Text>
              )}
            </Box>
          );
        })
      )}
    </Flex>
  );
}

function Group({
  title,
  subtitle,
  rows,
  modes,
}: {
  title: string;
  subtitle?: string;
  rows: Row[];
  modes: string[];
}) {
  if (!rows.length) return null;
  return (
    <Card radius={2} shadow={1} marginBottom={4} overflow="hidden">
      <Card padding={3} tone="transparent" borderBottom>
        <Flex align="center" gap={3}>
          <Text size={1} weight="semibold">
            {title}
          </Text>
          {subtitle && (
            <Text size={0} muted>
              {subtitle}
            </Text>
          )}
          <Box flex={1} />
          <Badge tone="primary" fontSize={0}>
            {rows.length}
          </Badge>
        </Flex>
      </Card>

      {/* column header: the modes */}
      {rows[0]?.value === undefined && (
        <Flex
          gap={3}
          paddingX={3}
          paddingY={2}
          style={{ borderBottom: "1px solid var(--card-border-color)" }}
        >
          <Box style={{ width: 230, flex: "none" }}>
            <Text size={0} muted weight="medium">
              TOKEN
            </Text>
          </Box>
          {modes.map((m) => (
            <Box key={m} flex={1} style={{ minWidth: 0 }}>
              <Text size={0} muted weight="medium" textOverflow="ellipsis">
                {m.toUpperCase()}
              </Text>
            </Box>
          ))}
        </Flex>
      )}

      {rows.map((row) => (
        <TokenRow key={row.path} row={row} modes={modes} />
      ))}
    </Card>
  );
}

function DesignTokensPanel() {
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState<"site" | "figma">("site");

  const q = query.trim().toLowerCase();
  const match = (rows: Row[]) =>
    !q
      ? rows
      : rows.filter(
          (r) =>
            r.path.toLowerCase().includes(q) ||
            (r.utility ?? "").toLowerCase().includes(q) ||
            Object.values(r.values ?? {}).some((v) =>
              String(v).toLowerCase().includes(q),
            ) ||
            String(r.value ?? "").toLowerCase().includes(q),
        );

  /* the Figma collection, grouped the way the variables panel groups it */
  const figmaGroups = useMemo(() => {
    const by = new Map<string, Row[]>();
    for (const t of index.figma.tokens as Row[]) {
      const group = t.path.split("/").slice(0, -1).join(" / ");
      if (!by.has(group)) by.set(group, []);
      by.get(group)!.push(t);
    }
    return [...by.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }, []);

  const siteModes = index.css.modes as string[];
  const figmaModes = index.figma.modes as string[];

  return (
    <Box padding={4} style={{ maxWidth: 1400, margin: "0 auto" }}>
      <Stack space={4}>
        <Flex align="flex-end" gap={4} wrap="wrap">
          <Stack space={3} flex={1}>
            <Text size={3} weight="semibold">
              Design tokens
            </Text>
            <Text size={1} muted>
              The Sun Day Red design library — every value the site is allowed to
              build from. Read-only: edit tokens in Figma, re-export, and run{" "}
              <code style={{ fontFamily: MONO }}>npm run tokens</code>.
            </Text>
          </Stack>
        </Flex>

        {/* provenance — when the tokens were last re-uploaded */}
        <Card padding={3} radius={2} tone="primary">
          <Flex gap={5} wrap="wrap">
            <Stack space={2}>
              <Text size={0} muted weight="medium">
                FIGMA VARIABLES LAST EXPORTED
              </Text>
              <Text size={1}>{relativeTime(index.sources.figma.updatedAt)}</Text>
            </Stack>
            <Stack space={2}>
              <Text size={0} muted weight="medium">
                SITE TOKENS LAST CHANGED
              </Text>
              <Text size={1}>{relativeTime(index.sources.css.updatedAt)}</Text>
            </Stack>
            <Stack space={2}>
              <Text size={0} muted weight="medium">
                INDEX GENERATED
              </Text>
              <Text size={1}>{relativeTime(index.generatedAt)}</Text>
            </Stack>
            <Stack space={2}>
              <Text size={0} muted weight="medium">
                MODES EXPORTED
              </Text>
              <Text size={1}>{figmaModes.length} of 6</Text>
            </Stack>
          </Flex>
        </Card>

        <Flex gap={2} align="center">
          {(
            [
              ["site", "Site tokens"],
              ["figma", "Figma library"],
            ] as const
          ).map(([id, label]) => (
            <Card
              key={id}
              as="button"
              padding={3}
              radius={2}
              tone={tab === id ? "primary" : "default"}
              shadow={tab === id ? 1 : 0}
              onClick={() => setTab(id)}
              style={{ cursor: "pointer", border: "none" }}
            >
              <Text size={1} weight={tab === id ? "semibold" : "regular"}>
                {label}
              </Text>
            </Card>
          ))}
          <Box flex={1}>
            <TextInput
              icon={icons["search"]}
              placeholder="Filter tokens, values, or utilities…"
              value={query}
              onChange={(e) => setQuery(e.currentTarget.value)}
              onClear={() => setQuery("")}
              clearButton={query.length > 0}
            />
          </Box>
        </Flex>

        {tab === "site" ? (
          <Box>
            <Group
              title="Color — semantic"
              subtitle="flips per data-mode wrapper; never hardcode a mode color"
              rows={match(index.css.semantic as Row[])}
              modes={siteModes}
            />
            <Group
              title="Spacing"
              subtitle="the Figma spacing scale"
              rows={match(index.css.spacing as Row[])}
              modes={siteModes}
            />
            <Group
              title="Typography"
              subtitle="fluid between the 428px and 1440px frames"
              rows={match(index.css.type as Row[])}
              modes={siteModes}
            />
            <Group
              title="Radius"
              rows={match(index.css.radius as Row[])}
              modes={siteModes}
            />
            <Group
              title="Fonts"
              rows={match(index.css.fonts as Row[])}
              modes={siteModes}
            />
          </Box>
        ) : (
          <Box>
            {figmaGroups.map(([group, rows]) => (
              <Group
                key={group}
                title={group}
                rows={match(rows)}
                modes={figmaModes}
              />
            ))}
          </Box>
        )}
      </Stack>
    </Box>
  );
}

export const designTokensTool: Tool = {
  name: "tokens",
  title: "Tokens",
  icon: icons["color-wheel"],
  component: DesignTokensPanel,
};
