"use client";

import { icons } from "@sanity/icons";
import { useMemo, useState } from "react";
import type { Tool } from "sanity";

import index from "@/design/tokens.index.json";

import { GlassChip, MONO, Shell, StatCard } from "./dash";

/*
  "Design tokens" — the Studio's read-only view of the design system,
  laid out like Figma's Variables panel on the dashboard skin: light
  cards of token rows, one column per mode, resolved values with
  swatches.

  Two tabs:
    · Site tokens   — what the code actually consumes (globals.css)
    · Figma library — the raw variable collection, every mode

  The data is generated by `npm run tokens` (scripts/build-token-
  index.mjs) into src/design/tokens.index.json, which also records
  when each source was last re-exported — shown in the hero.
*/

type Row = {
  path: string;
  name: string;
  type: string;
  values?: Record<string, string>;
  value?: string;
  aliasOf?: Record<string, string>;
  utility?: string | null;
  detail?: { lineHeight?: string; letterSpacing?: string };
};

const isColor = (v?: string) => !!v && /^(#|rgb|hsl|color\()/i.test(v.trim());

function relativeTime(iso?: string | null) {
  if (!iso) return "unknown";
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return "unknown";
  const days = Math.floor((Date.now() - then) / 86_400_000);
  const date = new Date(iso).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  if (days <= 0) return `${date} (today)`;
  if (days === 1) return `${date} (yesterday)`;
  return `${date} (${days} days ago)`;
}

function Swatch({ value }: { value: string }) {
  return (
    <span
      aria-hidden
      className="ovw-swatch"
      style={{
        background: value,
        /* alpha tokens read correctly over a checker */
        backgroundImage: `linear-gradient(${value}, ${value}), repeating-conic-gradient(#bbb 0% 25%, #fff 0% 50%)`,
        backgroundSize: "auto, 8px 8px",
      }}
    />
  );
}

/* one token = one row; a cell per mode */
function TokenRow({ row, modes }: { row: Row; modes: string[] }) {
  const single = row.value !== undefined;
  return (
    <div className="ovw-table-row">
      <div className="ovw-cell-name">
        <div className="ovw-mono" style={{ fontWeight: 500 }}>
          {row.name}
        </div>
        {row.utility && (
          <div className="ovw-mono ovw-muted" style={{ fontSize: 11 }}>
            {row.utility}
          </div>
        )}
      </div>

      {single ? (
        <div className="ovw-cell">
          <span className="ovw-mono">{row.value}</span>
          {(row.detail?.lineHeight || row.detail?.letterSpacing) && (
            <div className="ovw-mono ovw-muted" style={{ fontSize: 11 }}>
              {row.detail?.lineHeight && `line-height ${row.detail.lineHeight}`}
              {row.detail?.lineHeight && row.detail?.letterSpacing && "  ·  "}
              {row.detail?.letterSpacing && `tracking ${row.detail.letterSpacing}`}
            </div>
          )}
        </div>
      ) : (
        modes.map((mode) => {
          const v = row.values?.[mode];
          const alias = row.aliasOf?.[mode];
          return (
            <div key={mode} className="ovw-cell">
              {v ? (
                <>
                  <span style={{ whiteSpace: "nowrap" }}>
                    {isColor(v) && <Swatch value={v} />}
                    <span className="ovw-mono">{v}</span>
                  </span>
                  {alias && (
                    <div className="ovw-muted" style={{ fontSize: 11 }} title={alias}>
                      → {alias.split("/").pop()}
                    </div>
                  )}
                </>
              ) : (
                <span className="ovw-muted">—</span>
              )}
            </div>
          );
        })
      )}
    </div>
  );
}

function Group({
  title,
  subtitle,
  rows,
  modes,
}: {
  title: string;
  subtitle?: string;
  rows: Row[];
  modes: string[];
}) {
  if (!rows.length) return null;
  return (
    <StatCard
      title={
        <>
          {title}
          {subtitle ? <span className="ovw-muted"> · {subtitle}</span> : null}
          <span className="ovw-muted"> · {rows.length}</span>
        </>
      }
      size="full"
    >
      {rows[0]?.value === undefined && (
        <div className="ovw-table-row ovw-table-head">
          <div className="ovw-cell-name">TOKEN</div>
          {modes.map((m) => (
            <div key={m} className="ovw-cell">
              {m.toUpperCase()}
            </div>
          ))}
        </div>
      )}
      {rows.map((row) => (
        <TokenRow key={row.path} row={row} modes={modes} />
      ))}
    </StatCard>
  );
}

function DesignTokensPanel() {
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState<"site" | "figma">("site");

  const q = query.trim().toLowerCase();
  const match = (rows: Row[]) =>
    !q
      ? rows
      : rows.filter(
          (r) =>
            r.path.toLowerCase().includes(q) ||
            (r.utility ?? "").toLowerCase().includes(q) ||
            Object.values(r.values ?? {}).some((v) =>
              String(v).toLowerCase().includes(q),
            ) ||
            String(r.value ?? "").toLowerCase().includes(q),
        );

  /* the Figma collection, grouped the way the variables panel groups it */
  const figmaGroups = useMemo(() => {
    const by = new Map<string, Row[]>();
    for (const t of index.figma.tokens as Row[]) {
      const group = t.path.split("/").slice(0, -1).join(" / ");
      if (!by.has(group)) by.set(group, []);
      by.get(group)!.push(t);
    }
    return [...by.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }, []);

  const siteModes = index.css.modes as string[];
  const figmaModes = index.figma.modes as string[];

  return (
    <Shell
      active="tokens"
      wide
      title="Design Tokens"
      sub={
        <>
          Every value the site is allowed to build from — read-only: edit in Figma, re-export, run{" "}
          <code style={{ fontFamily: MONO }}>npm run tokens</code> · Figma exported{" "}
          {relativeTime(index.sources.figma.updatedAt)} · site tokens changed{" "}
          {relativeTime(index.sources.css.updatedAt)}
        </>
      }
      chip={
        <GlassChip
          label="Modes exported"
          value={`${figmaModes.length} / 6`}
          note={`index generated ${relativeTime(index.generatedAt)}`}
          warn={figmaModes.length < 6}
        />
      }
    >
      <div style={{ display: "flex", gap: 12, alignItems: "center", marginBottom: 16, flexWrap: "wrap" }}>
        <nav className="ovw-seg">
          {(
            [
              ["site", "Site tokens"],
              ["figma", "Figma library"],
            ] as const
          ).map(([id, label]) => (
            <button
              key={id}
              type="button"
              className={tab === id ? "is-active" : undefined}
              onClick={() => setTab(id)}
            >
              {label}
            </button>
          ))}
        </nav>
        <div style={{ flex: 1, minWidth: 240 }}>
          <input
            className="ovw-input"
            placeholder="Filter tokens, values, or utilities…"
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
          />
        </div>
      </div>

      <div className="ovw-grid">
        {tab === "site" ? (
          <>
            <Group
              title="Color — semantic"
              subtitle="flips per data-mode wrapper; never hardcode a mode color"
              rows={match(index.css.semantic as Row[])}
              modes={siteModes}
            />
            <Group title="Spacing" subtitle="the Figma spacing scale" rows={match(index.css.spacing as Row[])} modes={siteModes} />
            <Group
              title="Typography"
              subtitle="fluid between the 428px and 1440px frames"
              rows={match(index.css.type as Row[])}
              modes={siteModes}
            />
            <Group title="Radius" rows={match(index.css.radius as Row[])} modes={siteModes} />
            <Group title="Fonts" rows={match(index.css.fonts as Row[])} modes={siteModes} />
          </>
        ) : (
          figmaGroups.map(([group, rows]) => (
            <Group key={group} title={group} rows={match(rows)} modes={figmaModes} />
          ))
        )}
      </div>
    </Shell>
  );
}

export const designTokensTool: Tool = {
  name: "tokens",
  title: "Tokens",
  icon: icons["color-wheel"],
  component: DesignTokensPanel,
};
